########## Instructions
#First, create a folder called "derivatization" on the C drive of your computer. Then, create seven subfolders named "1", "2", "3", "4", "5", "6", "7"
#Second, put the csv file of the original sample into the folder "4", the column names are "m/z", "I", "S/N"
#Third, put the csv file of the derived sample into the folder "1", the column names are "m/z", "I", "S/N"
#Finally, run the following code in R.

#Please note the following:
  #Make sure the file names in folder "1" and folder "4" match.
  #Folder "2" and folder "5" are used to store the data generated by the calculation process.
  #Folder "3" and folder "6" are used to store the final data of the original and derived samples, including aggregated weighted parameters, respectively.
  #Folder "7" is used to store information about the carbonyl molecules of the sample.

########## loading package
library(dplyr)
library(sqldf)


########## building library (C1-60 H1-120 O1-40 N0-3 S0-1 F0,5,10,15)
options(digits=10) #Sets the number of decimal places

data <- matrix(nrow = 1000,ncol = 6) #C
colnames(data) <- c("F","S","N","O","H","C")
for(i in 1:60){
  data[i,6] <- i
}
data <- data[!is.na(data[,6]),]
datat <- matrix(rep(t(data),120),ncol=ncol(data),byrow=TRUE)
colnames(datat) <- c("F","S","N","O","H","C")

data <- matrix(nrow = 1000,ncol = 6) #CH
colnames(data) <- c("F","S","N","O","H","C")
for(i in 1:120){
  data[i,5] <- i
}
data <- data[!is.na(data[,5]),]
data <- data[rep(1:nrow(data),each=60),]
datat[,5] <- data[,5]

datat <- matrix(rep(t(datat),40),ncol=ncol(data),byrow=TRUE)

data <- matrix(nrow = 1000,ncol = 6) #CHO
colnames(data) <- c("F","S","N","O","H","C")
for(i in 1:40){
  data[i,4] <- i
}
data <- data[!is.na(data[,4]),]
data <- data[rep(1:nrow(data),each=7200),]
datat[,4] <- data[,4]

datat <- matrix(rep(t(datat),4),ncol=ncol(data),byrow=TRUE)

data <- matrix(nrow = 1000,ncol = 6)
colnames(data) <- c("F","S","N","O","H","C") #CHON
for(i in 1:4){
  data[i,3] <- i-1
}
data <- data[!is.na(data[,3]),]
data <- data[rep(1:nrow(data),each=288000),]
datat[,3] <- data[,3]

datat <- matrix(rep(t(datat),2),ncol=ncol(data),byrow=TRUE)

data <- matrix(nrow = 1000,ncol = 6) #CHONS
colnames(data) <- c("F","S","N","O","H","C")
for(i in 1:2){
  data[i,2] <- i-1
}
data <- data[!is.na(data[,2]),]
data <- data[rep(1:nrow(data),each=1152000),]
datat[,2] <- data[,2]

datat <- matrix(rep(t(datat),4),ncol=ncol(data),byrow=TRUE)

data <- matrix(nrow = 1000,ncol = 6) #CHONSF
colnames(data) <- c("F","S","N","O","H","C")
data[1,] <- c(0,0,0,0,0,0)
data[2,] <- c(5,0,1,0,2,7)
data[3,] <- c(10,0,2,0,4,14)
data[4,] <- c(15,0,3,0,6,21)
data <- data[!is.na(data[,1]),]
data <- data[rep(1:nrow(data),each=2304000),]
datat[,1] <- 0
datat <- datat + data


########## filtering rules
data <- matrix(nrow = 9216000,ncol = 10)
colnames(data) <- c("F","S","N","O","H","C","HC","OC","Molecularweight","DBE") # Column name
data <- as.data.frame(data)
data[,1:6] <- datat[,1:6]
data[,7:8] <- c(data[,5]/data[,6],data[,4]/data[,6]) # O/C < 1.2, H/C < 2.2
data1 <- subset(data,data$F==0&data[,7]<2.2&data[,8]<1.2)
data2 <- subset(data,data$F==5&(data[,5]-2)/(data[,6]-7)<2.2&data[,4]/(data[,6]-7)<1.2)
data3 <- subset(data,data$F==10&(data[,5]-4)/(data[,6]-14)<2.2&data[,4]/(data[,6]-14)<1.2)
data4 <- subset(data,data$F==15&(data[,5]-6)/(data[,6]-21)<2.2&data[,4]/(data[,6]-21)<1.2)
data <- rbind(data1,data2,data3,data4)
data1 <- subset(data,data$F==0)
data2 <- subset(data,data$F==5&(data[,6]-7)>=1&data[,4]>=1)
data3 <- subset(data,data$F==10&(data[,6]-14)>=2&data[,4]>=2)
data4 <- subset(data,data$F==15&(data[,6]-21)>=3&data[,4]>=3)
data <- rbind(data1,data2,data3,data4)
data[,9] <- 12.000000*data[,6] + 1.007825*data[,5] + 15.9949146*data[,4] + 14.003074*data[,3] + 31.9720707*data[,2] + 18.9984032*data[,1] # Molecular weight  
data1 <- subset(data,data$F==0&data[,9]<=800&data[,9]>=200&data$C>=5&data$H>=10)
data2 <- subset(data,data$F==5&data[,9]<=995.01074&data[,9]>=200)
data3 <- subset(data,data$F==10&data[,9]<=1190.02148&data[,9]>=390.02148)
data4 <- subset(data,data$F==15&data[,9]<=1385.03222&data[,9]>=585.03222)
data <- rbind(data1,data2,data3,data4)
data$DBE <- 1 + (data$C-data$F/5*7) - (data$H-data$F/5*2)/2 + (data$N-data$F/5)/2 
data <- subset(data,data[,10]<=50&data[,10]>=0) # 0 <= DBE <=50
data <- subset(data,(data[,10]-data[,4])<=10) # DBE-O <= 10
data$"N-rule" <- 12*data[,6] + 1*data[,5] + 16*data[,4] + 14*data[,3] + 32*data[,2] + 19*data[,1] # nitrogen rule
data1 <- subset(data,data$N==0&data$`N-rule`%%2==0)
data2 <- subset(data,data$N==1&data$`N-rule`%%2>0)
data3 <- subset(data,data$N==2&data$`N-rule`%%2==0)
data4 <- subset(data,data$N==3&data$`N-rule`%%2>0)
data5 <- subset(data,data$N==4&data$`N-rule`%%2==0)
data6 <- subset(data,data$N==5&data$`N-rule`%%2>0)
data7 <- subset(data,data$N==6&data$`N-rule`%%2==0)
data <- rbind(data1,data2,data3,data4,data5,data6,data7)
data8 <- data


########## Assign the molecular formula of the original sample
data <- subset(data,data$F==0)
data <- data[order(data$`Molecularweight`),]
inter<- 1000
file_names <- list.files("C:/derivatization/4/")
path <- c("C:/derivatization/4/")
for (i in 1:length(file_names)) {
  data2 <- data.frame()
  datasample <- read.csv(paste0(path,file_names[i]),header = TRUE, stringsAsFactors = FALSE)
  datasample <- datasample[!is.na(datasample$m.z),]
  datasample <- subset(datasample,datasample$S.N>=4)
  datasample <- datasample[order(datasample$m.z),]
  group <- nrow(datasample)%/%inter
  datasample[,3] <- datasample[,1]
  datasample[,1] <-  1.007825 + datasample[,1] - 0.0005485
  for(j in 1:group){
    data3 <- subset(data,data[,9]<=(datasample[j*inter,1]+0.005)&data[,9]>=(datasample[(j-1)*inter+1,1]-0.005))
    for(k in 1:inter){
      data1 <- subset(data3,data3[,9]<(datasample[(j-1)*inter+k,1]+0.001)&data3[,9]>(datasample[(j-1)*inter+k,1]-0.001))
      if(sum(data1[,"Molecularweight"])>0){
        data1$measured <- datasample[(j-1)*inter+k,1]
        data1$input <- datasample[(j-1)*inter+k,3]
        data1$I <- datasample[(j-1)*inter+k,2]
        data2 <- rbind(data2,data1)}
    }
  } 
  data3 <- subset(data,data[,9]>=(datasample[inter*group+1,1]-0.005)&data[,9]<=(datasample[nrow(datasample),1]+0.005))
  for(j in (inter*group+1):nrow(datasample)){
    data1 <- subset(data3,data3[,9]<(datasample[j,1]+0.001)&data3[,9]>(datasample[j,1]-0.001))
    if(sum(data1[,"Molecularweight"])>0){
      data1$measured <- datasample[j,1]
      data1$input <- datasample[j,3]
      data1$I <- datasample[j,2]
      data2 <- rbind(data2,data1)}
  } 
  data2$cha <- (abs(data2$measured - data2$`Molecularweight`))/data2$`Molecularweight`*1000000 # ppm <- 0.5
  data2 <- subset(data2,data2$cha <=0.5)
  for(x in 1:nrow(data2)){
    data2[x,"Molecularformula"] <- paste0("C",data2[x,6],"H",data2[x,5],"O",data2[x,4],"N",data2[x,3],"S",data2[x,2],"F",data2[x,1])
  }
  data2 <- data2[!is.na(data2[,2]),]
  data2$NS <- data2$N + data2$S - data2$F/5 # Heteroatomic minimum principle
  data2 <- group_by(data2,measured)
  data2 <- top_n(data2,n=-1,wt=NS)
  data2 <- group_by(data2,measured) # Minimum error
  data2 <- top_n(data2,n=-1,wt=cha)
  write.csv(data2,paste0("C:/derivatization/5/",file_names[i],".csv"))
}


########## Calculate the molecular parameters of the original sample
file_names <- list.files("C:/derivatization/5/")
path <- c("C:/derivatization/5/")
data2 <- matrix(nrow=length(file_names),ncol=14,dimnames=list(file_names,c("counts","C","H","O","N","S","H/C","O/C","DBE","NOSC","DBE/C",
                                                                           "AImod","MW","MLB"))) # Build a matrix that stores weighted parameters
data2 <- as.data.frame(data2)
for (i in 1:length(file_names)) {
  data <- read.csv(paste0(path,file_names[i]),header = TRUE, stringsAsFactors = FALSE)
  data1 <- sqldf("select input, I, Molecularformula, Molecularweight, cha, C, H ,O, N, S, F, OC, HC from data") 
  colnames(data1) <- c("m/z","I","Sumformula","cal.m/z","err(ppm)","C","H","O","N","S","F","O/C","H/C")
  data1$AImod <- (1 + data1$C - data1$H/2 - data1$O/2-data1$S)/(data1$C - data1$O/2 - data1$S- data1$N)
  data1$"I%(total)" <- data1$I/sum(data1$I)
  data1$"I%" <- 100*data1$I/max(data1$I)
  data1$rdb <- 1 + data1$C - data1$H/2 + data1$N/2
  data1$coo <- data1$O/2
  data1$'positiveAImod' <- abs(data1$AImod)
  data1$NOSC <- 4-(4*data1$C + data1$H - 3*data1$N - 2*data1$O - 2*data1$S)/data1$C 
  data1$CxI <- as.numeric(data1$I)*as.numeric(data1$C)
  data1$HxI <- as.numeric(data1$I)*as.numeric(data1$H)
  data1$NxI <- data1$I*data1$N 
  data1$OxI <- as.numeric(data1$I)*as.numeric(data1$O)
  data1$SxI <- data1$I*data1$S 
  data1$"H/CxI" <- data1$I*data1$`H/C`
  data1$"O/CxI" <- data1$I*data1$`O/C` 
  data1$DBE <- data1$I*data1$rdb
  data1$NOSCxI <- data1$I*data1$NOSC
  data1$"DBE/C" <- (data1$rdb/data1$H)*data1$I
  data1$Aimod <- data1$I*data1$positiveAImod
  write.csv(data1,paste0("C:/derivatization/6/",file_names[i],".csv")) 
  data2[i,] <- c(nrow(data1),sum(data1$CxI)/sum(data1$I),sum(data1$HxI)/sum(data1$I),
                 sum(data1$OxI)/sum(data1$I),sum(data1$NxI)/sum(data1$I),sum(data1$SxI)/sum(data1$I),
                 sum(data1$`H/CxI`)/sum(data1$I),sum(data1$`O/CxI`)/sum(data1$I),
                 sum(data1$DBE)/sum(data1$I),sum(data1$NOSCxI)/sum(data1$I),
                 sum(data1$`DBE/C`)/sum(data1$I),sum(data1$Aimod)/sum(data1$I),sum(data1$`cal.m/z`*data1$I)/sum(data1$I),
                 nrow(subset(data1,data1$`H/C`>1.5))/nrow(data1))
}
write.csv(data2,"C:/derivatization/6/Weighted parameter.csv")


########## Assign the molecular formula of the derived sample
data <- data8
data <- data[order(data$Molecularweight),]
inter<- 1000
file_names <- list.files("C:/derivatization/1/")
path <- c("C:/derivatization/1/")
file_namess <- list.files("C:/derivatization/6/")
paths <- c("C:/derivatization/6/")
for (i in 1:length(file_names)) {
  data4 <- read.csv(paste0(paths,file_namess[i]),header = TRUE, stringsAsFactors = FALSE)
  data2 <- data.frame()
  datasample <- read.csv(paste0(path,file_names[i]),header = TRUE, stringsAsFactors = FALSE)
  datasample <- datasample[!is.na(datasample$m.z),]
  datasample <- subset(datasample,datasample$S.N>=4)
  datasample <- datasample[order(datasample$m.z),]
  group <- nrow(datasample)%/%inter
  datasample[,3] <- datasample[,1]
  datasample[,1] <-  1.007825 + datasample[,1] - 0.0005485
  for(j in 1:group){
    data3 <- subset(data,data[,9]<=(datasample[j*inter,1]+0.005)&data[,9]>=(datasample[(j-1)*inter+1,1]-0.005))
    for(k in 1:inter){
      data1 <- subset(data3,data3[,9]<(datasample[(j-1)*inter+k,1]+0.001)&data3[,9]>(datasample[(j-1)*inter+k,1]-0.001))
      if(sum(data1[,"Molecularweight"])>0){
        data1$measured <- datasample[(j-1)*inter+k,1]
        data1$input <- datasample[(j-1)*inter+k,3]
        data1$I <- datasample[(j-1)*inter+k,2]
        data2 <- rbind(data2,data1)}
    }
  } 
  data3 <- subset(data,data[,9]>=(datasample[inter*group+1,1]-0.005)&data[,9]<=(datasample[nrow(datasample),1]+0.005))
  for(j in (inter*group+1):nrow(datasample)){
    data1 <- subset(data3,data3[,9]<(datasample[j,1]+0.001)&data3[,9]>(datasample[j,1]-0.001))
    if(sum(data1[,"Molecularweight"])>0){
      data1$measured <- datasample[j,1]
      data1$input <- datasample[j,3]
      data1$I <- datasample[j,2]
      data2 <- rbind(data2,data1)}
  } 
  data2$cha <- (abs(data2$measured - data2$Molecularweight))/data2$'Molecularweight'*1000000 # ppm <- 0.5
  data2 <- subset(data2,data2$cha <=0.5)
  
  
  for(x in 1:nrow(data2)){
    data2[x,"Molecularformula"] <- paste0("C",data2[x,6],"H",data2[x,5],"O",data2[x,4],"N",data2[x,3],"S",data2[x,2],"F",data2[x,1])
    if(data2[x,"F"] >0){
      if(data2[x,"Molecularweight"]- data2[x,"F"]/5*195.01074 >= 200){
        if(paste0("C",data2[x,6]-data2[x,"F"]/5*7,"H",data2[x,5]-data2[x,"F"]/5*2,"O",data2[x,4],"N",data2[x,3]-data2[x,"F"]/5*1,"S",data2[x,2],"F",data2[x,1]-data2[x,"F"]/5*5) %in% data4$Sumformula == FALSE){
          data2[x,] <-  NA
        }
      }
    }
  }
  data2 <- data2[!is.na(data2[,2]),]
  
  data2$NS <- data2$N + data2$S - data2$F/5 # Heteroatomic minimum principle
  data2 <- group_by(data2,measured)
  data2 <- top_n(data2,n=-1,wt=NS)
  data2 <- group_by(data2,measured) # Minimum error
  data2 <- top_n(data2,n=-1,wt=cha)
  write.csv(data2,paste0("C:/derivatization/2/",file_names[i],".csv"))
}


########## Calculate the molecular parameters of the derived sample
file_names <- list.files("C:/derivatization/2/")
path <- c("C:/derivatization/2/")
data2 <- matrix(nrow=length(file_names),ncol=18,dimnames=list(file_names,c("counts","C","H","O","N","S","H/C","O/C","DBE","NOSC","DBE/C",
                                                                           "AImod","MW","MLB","one","two","three","total"))) # Build a matrix that stores weighted parameters
data2 <- as.data.frame(data2)
for (i in 1:length(file_names)) {
  data <- read.csv(paste0(path,file_names[i]),header = TRUE, stringsAsFactors = FALSE)
  data1 <- sqldf("select input, I, Molecularformula, Molecularweight, cha, C, H ,O, N, S, F, OC, HC from data") 
  colnames(data1) <- c("m/z","I","Sumformula","cal.m/z","err(ppm)","C","H","O","N","S","F","O/C","H/C")
  data1$AImod <- (1 + data1$C - data1$H/2 - data1$O/2-data1$S)/(data1$C - data1$O/2 - data1$S- data1$N)
  data1$"I%(total)" <- data1$I/sum(data1$I)
  data1$"I%" <- 100*data1$I/max(data1$I)
  data1$rdb <- 1 + data1$C - data1$H/2 + data1$N/2
  data1$coo <- data1$O/2
  data1$'positiveAImod' <- abs(data1$AImod)
  data1$NOSC <- 4-(4*data1$C + data1$H - 3*data1$N - 2*data1$O - 2*data1$S)/data1$C 
  data1$CxI <- as.numeric(data1$I)*as.numeric(data1$C)
  data1$HxI <- as.numeric(data1$I)*as.numeric(data1$H)
  data1$NxI <- data1$I*data1$N 
  data1$OxI <- as.numeric(data1$I)*as.numeric(data1$O)
  data1$SxI <- data1$I*data1$S 
  data1$"H/CxI" <- data1$I*data1$`H/C`
  data1$"O/CxI" <- data1$I*data1$`O/C` 
  data1$DBE <- data1$I*data1$rdb
  data1$NOSCxI <- data1$I*data1$NOSC
  data1$"DBE/C" <- (data1$rdb/data1$H)*data1$I
  data1$Aimod <- data1$I*data1$positiveAImod
  for(y in 1:nrow(data1)){
    data1[y,"Originalformula"] <- paste0("C",data1[y,"C"]-data1[y,"F"]/5*7,"H",data1[y,"H"]-data1[y,"F"]/5*2,"O",data1[y,"O"],"N",data1[y,"N"]-data1[y,"F"]/5*1,"S",data1[y,"S"],"F",data1[y,"F"]-data1[y,"F"]/5*5)
  }
  data1$Originalmolecularweight <- data1$`cal.m/z` - 195.01074*(data1$F/5)
  write.csv(data1,paste0("C:/derivatization/3/",file_names[i],".csv"))
  data3 <- data1[!is.infinite(data1$Aimod),]
  data2[i,] <- c(nrow(data1),sum(data1$CxI)/sum(data1$I),sum(data1$HxI)/sum(data1$I),
                 sum(data1$OxI)/sum(data1$I),sum(data1$NxI)/sum(data1$I),sum(data1$SxI)/sum(data1$I),
                 sum(data1$`H/CxI`)/sum(data1$I),sum(data1$`O/CxI`)/sum(data1$I),
                 sum(data1$DBE)/sum(data1$I),sum(data1$NOSCxI)/sum(data1$I),
                 sum(data1$`DBE/C`)/sum(data1$I),sum(data1$Aimod)/sum(data1$I),sum(data1$`cal.m/z`*data1$I)/sum(data1$I),
                 nrow(subset(data1,data1$`H/C`>1.5))/nrow(data1),sum(data1$F==5),sum(data1$F==10),sum(data1$F==15),
                 sum(data1$F==5)+sum(data1$F==10)+sum(data1$F==15))
}
write.csv(data2,"C:/derivatization/3/Weighted parameter.csv")


########## Carbonyl molecules in the sample
file_names1 <- list.files("C:/derivatization/6/")
path1 <- c("C:/derivatization/6/")
file_names2 <- list.files("C:/derivatization/3/")
path2 <- c("C:/derivatization/3/")
for (i in 1:(length(file_names2)-1)){
  data1 <- read.csv(paste0(path2,file_names2[i]))
  data2 <- read.csv(paste0(path1,file_names1[i]))
  data3 <- subset(data1,data1$F==15)
  data3 <- data3$Originalformula
  data3 <- data3[!duplicated(data3)]
  data3 <- as.matrix(data3)
  data4 <- data2[match(data3[,1],data2[,4]),1:32]
  data4 <- data4[!is.na(data4$Sumformula),]
  if(nrow(data4) > 0){
    data4$Carbonylnumber <- 3}
  data3 <- subset(data1,data1$F==10)
  data3 <- data3$Originalformula
  data3 <- data3[!duplicated(data3)]
  data3 <- as.matrix(data3)
  data5 <- data2[match(data3[,1],data2[,4]),1:32]
  data5 <- data5[!is.na(data5$Sumformula),]
  if(nrow(data5) > 0){
    data5$Carbonylnumber <- 2}
  data3 <- subset(data1,data1$F==5)
  data3 <- data3$Originalformula
  data3 <- data3[!duplicated(data3)]
  data3 <- as.matrix(data3)
  data6 <- data2[match(data3[,1],data2[,4]),1:32]
  data6 <- data6[!is.na(data6$Sumformula),]
  if(nrow(data6) > 0){
    data6$Carbonylnumber <- 1}
  data4 <- rbind(data4,data5,data6)
  data4 <- group_by(data4,Sumformula)
  data4 <- top_n(data4,n=1,wt=Carbonylnumber)
  write.csv(data4,paste0("C:/derivatization/7/",file_names2[i],".csv"))
}
file_names <- list.files("C:/derivatization/7/")
path <- c("C:/derivatization/7/")
data2 <- matrix(nrow=length(file_names),ncol=15,dimnames=list(file_names,c("counts","C","H","O","N","S","H/C","O/C","DBE","NOSC","DBE/C",
                                                                           "AImod","MW","MLB","I"))) # Build a matrix that stores weighted parameters
for (i in 1:length(file_names)) {
  data1 <- read.csv(paste0(path,file_names[i]),header = TRUE, stringsAsFactors = FALSE)
  data2[i,] <- c(nrow(data1),sum(data1$CxI)/sum(data1$I),sum(data1$HxI)/sum(data1$I),
                 sum(data1$OxI)/sum(data1$I),sum(data1$NxI)/sum(data1$I),sum(data1$SxI)/sum(data1$I),
                 sum(data1$`H.CxI`)/sum(data1$I),sum(data1$`O.CxI`)/sum(data1$I),
                 sum(data1$DBE)/sum(data1$I),sum(data1$NOSCxI)/sum(data1$I),
                 sum(data1$`DBE.C`)/sum(data1$I),sum(data1$Aimod)/sum(data1$I),sum(data1$`cal.m.z`*data1$I)/sum(data1$I),
                 nrow(subset(data1,data1$`H.C`>1.5))/nrow(data1),sum(data1$I..total.))
}
write.csv(data2,"C:/derivatization/7/Weighted parameter.csv")
